- hosts: devbox
  gather_facts: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600
      become: yes
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'  
  
  vars:
      pip_executable: pip3
      pip_install_packages:
        - name: ansible-vault
        - name: invoke
        - name: docker
        - name: awscli  
        - name: boto3
        - name: requests
        
      java_packages:
        - openjdk-8-jdk
        
  roles:
    - geerlingguy.firewall
    - geerlingguy.java
    - geerlingguy.pip
    - geerlingguy.java
    - geerlingguy.docker
    - geerlingguy.nodejs
    - sansible.zookeeper
    - sansible.kafka